### ISSUE TITLE
Update README with pkg.go.dev link

### ISSUE THREAD

**Issue by gstachni** [datastax-ext/astra-go-sdk#39]
Add a link to https://pkg.go.dev/github.com/datastax-ext/astra-go-sdk in the README

**Comment by SpencerC** [comment]
There is a link at the top:

https://github.com/datastax-ext/astra-go-sdk/blob/0bf4bffb7ec068a8a10b5a33e482529d5a9f5e1d/README.md?plain=1#L5

I think people looking at Go libraries all day will look for it here, but LMK if you'd prefer it more explicitly elsewhere as well.
